# Generated by Django 3.0.4 on 2020-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200405_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='times',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='第几次'),
        ),
    ]
