# Generated by Django 3.0.4 on 2020-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200405_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='生成多少唯一码'),
        ),
    ]
