# Generated by Django 3.0.4 on 2020-04-05 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200405_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ClassList'),
        ),
    ]
